;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "wine"
        "minetest"
        "torbrowser"
        "qbittorrent-enhanced"
        "surf"
        "steam"
        "mpv"
        "yt-dlp"
        "emacs-telega-contrib"
        "emacs-telega"
        "emacs-telega-server"
        "telegram-desktop"
        "cmake"
        "emacs"
        "w3m"
        "pamixer"
        "pavucontrol"
        "icecat"
        "gimp"
        "pipewire"
        "arandr"
        "ani-cli"
        "emacs-guix"
        "emacs-pdf-tools"
        "tdlib"
        "texlive"
        "feh"
        "picom"
        "git"
        "imagemagick"
        "protonup-ng"
        "tor-client"
        "hyfetch"
        "curl"
        "emacs-cyberpunk-theme"
        "rtorrent"
        "emacs-mentor"
        "emacs-deferred"
        "ghc-emojis"
        "emacs-auto-dictionary-mode"
        "unzip"
        "emacs-rainbow-delimiters"
        "ntfs-3g"
        "font-google-noto"
        "make"
        "xrandr"
        "torsocks"
        "unicode-emoji"
        "hunspell"
        "hunspell-dict-en"
        "aspell-dict-en"
        "uwufetch"))
